export { default as Signup } from './pages/Signup/SignUp'
export { default as Login } from './pages/Login/index'
export { default as ForgotPassword } from './pages/ForgetPassword/ForgetPassword'
export { default as ResetPassword } from './pages/ForgetPassword/ResetPassword'
export { default as Profile } from './pages/Profile/Profile'
export { default as PageNotFound } from './pages/ErrorTemplates/PageNotFound'
export { default as Forbidden } from './pages/ErrorTemplates/ForbiddenPage'
export { default as DashBoard } from './pages/UserDashBoard/DashBoard'
export { default as EmailOtp } from './pages/EmailandPhoneConfirmation/EmailOtp'
export { default as PhoneNbrVerify } from './pages/EmailandPhoneConfirmation/PhoneNbrVerify'
export { default as PhoneOtp } from './pages/EmailandPhoneConfirmation/PhoneOtp'
export { default as CreateTest } from './pages/Test/CreateTest'
export { default as SetQuestions } from './pages/Test/SetQuestions'
export { default as PostJob } from './pages/postJob/PostJob'
export { default as CompanyRegistration } from './pages/RegisterCompany/RegisterCompany'
export { default as Registration } from './pages/Registration/Registration'
export { default as Home } from './pages/Home/Home'
export { default as JobListing } from './pages/JobListing/JobListing'
export { default as JobDescription } from './pages/JobDescription/JobDescription'
export { default as Quiz } from './pages/Quiz/Quiz'
export { default as CompanyView } from './pages/CompanyView/CompanyView'
export { default as SuccessMsg } from './pages/SuccessMsg/SuccessMsg'
export { default as CompanyDashBoard } from './pages/CompanyDashboard/Dashboard'
export { default as CompanyReviews } from './pages/CompanyReviews/Reviews'
export { default as LandingPage } from './pages/LandingPage/Landing'

//to be excluded later on
export { default as Preview } from './components/ImageInput/ImgPreview'
